### ISSUE TITLE
[BUG] Cannot install the Emulsify UI Kit with the CLI

### ISSUE THREAD

**Issue by amazingrando** [emulsify-ds/emulsify-cli#233]
**Describe the bug**
I'm trying to install the Emulsify UI Kit component library with the Emulsify CLI and I cannot.

**To Reproduce**
1. Go to the [Standalone installation instructions](https://www.emulsify.info/docs/emulsify-drupal#standalone-for-prototyping-outside-of-a-drupal-install)
2. Change the following 
`emulsify system install --repository https://github.com/emulsify-ds/compound.git --checkout [branch/tag/commit]` to `emulsify system install --repository https://github.com/emulsify-ds/emulsify-ui-kit.git --checkout main`
3. Get the error `Unable to install system assets and/or required components: Error: ENOENT: no such file or directory, lstat '/Users/oest/.emulsify/cache/systems/aafceee31da1cd49aa7dc52ebb708c40/compound/src/components/00-base/01-colors'`

I updated [system.emulsify.json](https://github.com/emulsify-ds/emulsify-ui-kit/blob/main/system.emulsify.json) using the [instructions in the docs](https://www.emulsify.info/docs/supporting-projects/emulsify-cli/defining-a-custom-system).

Any help would be appreciated. TY.

**Comment by mikeethedude** [comment]
Ah. I think I do actually. Going to look at this soon this week here.

**Comment by mikeethedude** [comment]
So the error you are getting @joetower is because https://github.com/emulsify-ds/emulsify-ui-kit/blob/main/system.emulsify.json doesn't contain a "components" key inside of the variants object. (See: https://github.com/emulsify-ds/emulsify-cli/blob/develop/src/handlers/systemInstall.ts#L229C40-L229C40) Should we make it so UI Kit provides some info on required components or at at try an empty set of components? Or I can make it so we check if we have components and then skip the whole thing when it isn't setup. (Might be preferred @amazingrando ?)

**Comment by amazingrando** [comment]
Resolved by #115
