### ISSUE TITLE
Writing files takes forever

### ISSUE THREAD

**Issue by patrickocoffeyo** [emulsify-ds/emulsify-cli#25]
When running certain commands that include writing to files (init for example), `fs.writeFile` is taking forever to actually write. Need to look into why this is happening, and resolve.

**Comment by ModulesUnraveled** [comment]
I'm glad you mentioned this, because I was noticing the init command is a lot slower than our old php script

**Comment by patrickocoffeyo** [comment]
Yeah, I'm not exactly sure why it's taking so long

**Comment by patrickocoffeyo** [comment]
Hmm, upon further inspection, I am incorrect. Writing to the config files is actually not taking a long time, it's actually running `npm install` that is taking up time.

That explains why it's slower than the PHP script, as the PHP script doesn't install dependencies (you are expected to do that on your own).

**Comment by ModulesUnraveled** [comment]
That makes sense. And explains why I had a package-lock.json and node_modules... I wasn't expecting those. I wonder whether that should happen actually because I didn't have the right node version being used on the initial install, so I had to delete those files and then run `nvm use` and then `npm install` again anyway

**Comment by patrickocoffeyo** [comment]
Hmm, well we do need to install node modules before executing the init script, because the init script could (and in our case does) pull in external dependencies. Perhaps we should put a node version check in place before proceeding with initialization?
