### ISSUE TITLE
Starter instruction

### ISSUE THREAD

**Issue by christianwiedemann** [emulsify-ds/emulsify-cli#4]
Hi Emlusify team,

Is there some kind of starter instructions or starter repository which uses the cli? 
I can install it run test etc. but I miss the link how to use it install my first component set. 

Thanks!

**Comment by patrickocoffeyo** [comment]
Hey there @christianwiedemann! 

That's a great question. As of now, we do not have any starter instructions, nor do we have a starter repository that makes use of the CLI. During this quarter, our primary goal is to harden various aspects of the CLI so that it can be used without any obvious hiccups. Part of that goal includes some basic documentation, as well as standing up a simple Drupal website that makes use of the Drupal Emulsify starter and the Compound system via the CLI.

Once we have some documentation and examples, I'll respond back with references!

Kind regards

**Comment by amazingrando** [comment]
For future folks, the docs have moved to https://docs.emulsify.info/supporting-projects/emulsify-cli/emulsify-cli-usage.
