### ISSUE TITLE
Error handling when you pass a named system and a repository url

### ISSUE THREAD

**Issue by ModulesUnraveled** [emulsify-ds/emulsify-cli#70]
Currently, if you install a named system and pass a repository, the repository is ignored. We should add help text to say "Only pass one or the other"

e.g. `emulsify system install compound --repository https://github.com/emulsify-ds/compound.git --checkout 1.0.0` will appear to work, but will install the latest from `main` rather than `1.0.0` since the name `compound` is also passed. It seems to ignore the stuff that comes after it.

**Comment by calebtr-metro** [comment]
I confirm that this happens when the repository name does not end in .git.

The unexpected behavior is that emulsify-cli doesn't quit when it finds this error - it moves on to trying to get the repo by name.

Would the desired behavior be to exit-on-error when the repo url does not end in .git ? 

Or attempt to add .git ?

**Comment by calebtr-metro** [comment]
Exiting on error makes the most sense to me. 

Adding the extension when someone forgets it would be clever, but not necessarily expected, and would still require error handling.
